import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowUpRight, ArrowDownLeft, MessageSquare, DollarSign } from "lucide-react";
import { formatTokens, formatCost } from "../../lib/format";
import { providerColors } from "../../lib/colors";
import type { UsageStats, ProviderType, SourceType } from "../../lib/types";

interface Props {
  stats: UsageStats | null;
  providerType: ProviderType;
  sourceType?: SourceType;
}

function Tooltip({ text }: { text: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 4 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 4 }}
      transition={{ duration: 0.15 }}
      className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2 py-1 rounded-md text-[9px] text-text whitespace-nowrap z-10 border border-border-light pointer-events-none"
      style={{ backgroundColor: "var(--theme-bg)", backdropFilter: "blur(12px)" }}
    >
      {text}
    </motion.div>
  );
}

export function StatCards({ stats, providerType, sourceType }: Props) {
  const colors = providerColors[providerType];
  const [hoveredCard, setHoveredCard] = useState<string | null>(null);

  const isApi = sourceType === "api";

  const cards = [
    {
      label: "Input",
      value: stats ? formatTokens(stats.totalInputTokens) : "\u2014",
      icon: ArrowDownLeft,
      color: colors.main,
      tooltip: "Tokens sent to AI (prompts, code, etc.)",
    },
    {
      label: "Output",
      value: stats ? formatTokens(stats.totalOutputTokens) : "\u2014",
      icon: ArrowUpRight,
      color: colors.light,
      tooltip: "Tokens generated by AI (responses, code, etc.)",
    },
    ...(isApi ? [
      {
        label: "Sessions",
        value: "N/A",
        icon: MessageSquare,
        color: "#8b8b9e",
        tooltip: "Session tracking not available via API",
      },
      {
        label: "Cost",
        value: stats ? formatCost(stats.estimatedCostUsd) : "\u2014",
        icon: DollarSign,
        color: "#22c55e",
        tooltip: "Estimated API usage cost (USD)",
      },
    ] : [
      {
        label: "Sessions",
        value: stats ? stats.totalSessions.toString() : "\u2014",
        icon: MessageSquare,
        color: "#8b8b9e",
        tooltip: "Total coding sessions",
      },
      {
        label: "Messages",
        value: stats ? stats.totalMessages.toString() : "\u2014",
        icon: MessageSquare,
        color: "#8b8b9e",
        tooltip: "Total messages exchanged with AI",
      },
    ]),
  ];

  return (
    <div className="grid grid-cols-2 gap-2">
      {cards.map((card, i) => (
        <motion.div
          key={card.label}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.05 * i, duration: 0.3 }}
          className="group relative p-3 rounded-lg bg-card border border-border hover:border-border-light hover:bg-card-hover transition-all duration-200 cursor-default"
          onMouseEnter={() => setHoveredCard(card.label)}
          onMouseLeave={() => setHoveredCard(null)}
        >
          <AnimatePresence>
            {hoveredCard === card.label && <Tooltip text={card.tooltip} />}
          </AnimatePresence>
          <div className="flex items-center justify-between mb-1.5">
            <span className="text-[10px] font-medium text-muted uppercase tracking-wider">
              {card.label}
            </span>
            <card.icon size={12} style={{ color: card.color }} className="opacity-60" />
          </div>
          <div className="text-base font-bold text-text tabular-nums">{card.value}</div>
        </motion.div>
      ))}
    </div>
  );
}
